import Head from "next/head";
import Image from "next/image";
import { FormEvent } from "react";

export default function Login() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="text-red-600 text-4xl font-bold flex justify-center">
				Login Page
			</h1>
			{/* <Image src={logopicture} alt="logo for shopping list">
				<p>logo</p>
			</Image> */}
			<div className="flex flex-col items-center justify-center pt-3 gap-3">
				<input
					type="text"
					placeholder="e-mail"
					className=" w-50 h-10  rounded-md border border-slate-400 hover:border-slate-600"
				/>
				<input
					type="text"
					placeholder="password"
					className="w-50 h-10 py-5 rounded-md border border-slate-400 hover:border-slate-600"
				/>
				<a href="#">continue without account</a>
			</div>
		</>
	);
}
