import Head from "next/head";
import Image from "next/image";
import { FormEvent } from "react";

export default function Login() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="text-red-300 text-4xl font-bold flex justify-center pb-10">
				Login Page
			</h1>
			{/* Logo section */}
			{/* <Image src={logopicture} alt="logo for shopping list">
				<p>logo</p>
			</Image> */}

			{/* <a href="#">continue without account</a> */}

			<form
				action="/send-data-here"
				method="post"
				className="flex flex-col items-center justify-center pt-3 gap-5"
			>
				<input
					type="text"
					id="email"
					name="email"
					placeholder="E-mail"
					className=" w-60 h-10 text-center rounded-md border border-slate-400 hover:border-slate-600"
				/>

				<input
					type="password"
					id="password"
					name="password"
					placeholder="password"
					className=" w-60 h-10 text-center rounded-md border border-slate-400 hover:border-slate-600"
				/>
				<button
					type="submit"
					className=" w-32 h-10 bg-gray-300 rounded-md border border-slate-400 hover:border-slate-600"
				>
					Go
				</button>
				<button
					type="submit"
					className=" w-32 h-10 bg-gray-300 rounded-md border border-slate-400 hover:border-slate-600"
				>
					Register
				</button>
			</form>
		</>
	);
}
