
GET http://localhost:3000/api/test

###

GET http://localhost:3000/api/autocomplete?name=ban


###

DELETE http://localhost:3000/api/deleteList
Content-Type: application/json

{
  "id": "123456789"
}

###

POST http://localhost:3000/api/addItem
Content-Type: application/json

{
  "query": "shampoo",
  "inputList": "682e5c46-f53e-49b5-9720-245afc58c686"
}

###

GET http://localhost:3000/api/listItems?inputList=1e3e64e1-bbb4-4b31-b829-772694127995

###
