
# GET http://localhost:3000/api/test

# ###
# GET http://localhost:3000/api/autocomplete?name=pear


# ###
# GET http://localhost:3000/api/seeLists?id=43b20ffc-ceea-43d5-b08c-9a1a6e4a1f98


###
PATCH http://localhost:3000/api/updateListName
Content-Type: application/json

{
  "id": "3c34daba-20e9-4a99-b3fb-204406a63c37",
  "newName": "marias List"
}

# GET http://localhost:3000/api/seeLists?id=123456789
