import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useSession } from "next-auth/react";

export default function SignIn() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="text-red-600 text-4xl font-bold flex justify-center">
				SignIn
			</h1>
		</>
	);
}

const { data: session, status } = useSession();
