import type {
	GetServerSidePropsContext,
	InferGetServerSidePropsType,
} from "next";
import { getCsrfToken } from "next-auth/react";
import Head from "next/head";

export default function SignIn({
	csrfToken,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<form method="post" action="/api/auth/signin/email">
				<input name="csrfToken" type="hidden" defaultValue={csrfToken} />
				<label>
					Email address
					<input type="email" id="email" name="email" />
				</label>
				<button type="submit">Sign in with Email</button>
			</form>
		</>
	);
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
	const csrfToken = await getCsrfToken(context);
	return {
		props: { csrfToken },
	};
}
