import Head from "next/head";

export default function VerifyRequest() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="w-screen h-screen rounded-lg bg-primary-frame">
				<div className="flex flex-col items-centre justify-center">
					<div className=" bg-primary-frame w-80 h-38 rounded-lg drop-shadow-md mx-14 mt-52">
						<h1 className="text-center gap-3 font-sans p-4">
							Thanks! <br />
							Please check your Inbox <br />
							<br />a link has been sent to the E-Mail address you
							entered
						</h1>
					</div>
				</div>
			</div>
		</>
	);
}
