import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

export default function Launch() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex flex-col items-center p-10 gap-8 py-36">
				<div className="w-52 h-40 bg-slate-400 rounded-3xl"> </div>
				<p className="text-lg">welcome to shopping App!</p>
				<button className=" bg-slate-400 w-40 h-10 self-center rounded-md">
					get started
				</button>
			</div>
		</>
	);
}
