import { LargeButton } from "@/components/LargeButton";
import Head from "next/head";
import Link from "next/link";



export default function Splash() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className=" font-bold flex justify-center">
        Welcome to FullList,
      </h1>
     <Link href={"/login"}>
     <LargeButton variant={"primary"} label={"get started"} disabled={false}></LargeButton>
     </Link>
      
    
    </>
  );
}