import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="text-red-600 text-4xl font-bold flex justify-center">
				Home page
			</h1>
			<div className=" w-414px h-82px flex flex-row justify-space-between p-4">
				<h3>HEY, BEAUTIFUL</h3>
			</div>
			<div className=" w-screen">
				<input
					type="text"
					placeholder="Search"
					className=" border border-slate-300 rounded-lg w-full ml-4 mr-10 p-3"
				/>
			</div>
		</>
	);
}
