import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1 className="text-red-600 text-4xl font-bold flex justify-center">
				Home page
			</h1>
			<div className=" w-screen bg-slate-200 flex fle-row items-center justify-around">
				<h3 className="  flex flex-row text-center">Hey, beautiful</h3>
				<button className=" rounded-xxl text-xs bg-slate-400">1</button>
			</div>
			<div className=" w-25 h-6 bg-slate-300 rounded-lg mt-4 mx-14 p-1">
				<h4 className=" text-xs">Search</h4>
			</div>
		</>
	);
}
