import Head from "next/head";
import TabAccountSetting from "@/components/TabAccountSetting";
import { HeaderWithBack } from "@/components/HeaderWithBack";

export default function Settings() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderWithBack label={""} sendTo={"/home"} />
      <div className="">
        <div className="flex justify-center text-text-white">
          <TabAccountSetting />
        </div>
      </div>
    </>
  );
}
