import CardsWrapper from "@/components/CardsWrapper";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-screen-sm h-screen gap-2 justify-self-center">
        <h1 className="text-text-typo text-title">Landing Page</h1>
        <div className="">
          <CardsWrapper user_id="43b20ffc-ceea-43d5-b08c-9a1a6e4a1f98"/>
        </div>
      </div>
    </>
  );
}
