import { LargeButton } from "@/components/LargeButton";
import Head from "next/head";
import { FiChevronLeft, FiUser } from "react-icons/fi";
import { Transition } from "@headlessui/react";
import { FormEvent, useState } from "react";
import { signIn } from "next-auth/react";
import router from "next/router";

type buttonProps = {
	variant: "primary";
	label: string;
	disable: boolean;
};

export default function Settings(props: buttonProps) {
	const [email, setEmail] = useState("");
	const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
		e.preventDefault();
		signIn("email", { email });
	};
	const goBack = () => {
		router.push("/account");
	};
	const emailCheck = new RegExp(`[A-z]+@[a-z]+.com`);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="px-8 flex flex-col bg-grad-frame">
				<header className="w-full flex items-center h-10 pt-8">
					<a href="" onClick={goBack}>
						<FiChevronLeft size={28} />
					</a>
				</header>
				<div className="w-full flex-grow flex flex-col justify-around">
					<div className="flex bg-slate-400 w-full ">Account vs settings</div>
					<div className="flex w-full flex-col items-center gap-5">
						{/* This section will change depending on the account status of the User */}
						<div>
							<FiUser size={28} />
						</div>
						<form onSubmit={handleSubmit} className="flex flex-col">
							<input
								type="text"
								className=" w-96 p-2 m-2 ml-22 rounded-md border border-primary-default-Solid bg-transparent text-center"
								placeholder="Email"
								onChange={(e) => setEmail(e.target.value)}
							/>

							<Transition
								show={emailCheck.test(email)}
								enter="transform transition duration-400"
								enterFrom="opacity-0 scale-y-0"
								enterTo="opacity-100 scale-y-100"
								leave="transform duration-400 transition ease-in-out"
								leaveFrom="opacity-100 scale-y-100"
								leaveTo="opacity-0 scale-y-0"
							>
								<LargeButton
									variant="primary"
									label="Get new link"
									disabled={false}
								/>
							</Transition>
						</form>
					</div>
				</div>
			</div>
		</>
	);
}
function setEmail(value: string): void {
	throw new Error("Function not implemented.");
}
