import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

export default function SignIn() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<form
				action="/send-data-here"
				method="post"
				className="flex flex-col text-center p-10 gap-2"
			>
				<label> Sign up with email</label>
				<input
					className="w-30 h-10 border-slate-500 border-2 rounded-md px-2
                    "
					type="email"
					name="email"
					placeholder="email"
				/>
				<input
					className="w-30 h-10 border-slate-500 border-2 rounded-md px-2"
					type="password"
					name="password"
					placeholder="password"
				/>
				<button
					className="bg-blue-500 w-20 self-center rounded-md"
					type="submit"
				>
					Submit
				</button>
				<div className="gap-3">
					<button>Sign up with gmail</button>
					<div className="flex justify-center">
						<p>already have an account?&nbsp;</p>
						<a href="">log in here</a>
					</div>
					<a href="">continue without account</a>
				</div>
			</form>
		</>
	);
}
